apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: kustomize-lab
build:
  artifacts:
    - image: iteam1337/kustomize-lab-api
      context: packages/api
deploy:
  kubectl:
    manifests:
      - k8s/ns.yaml
      - k8s/api.yaml
    flags:
      global:
        - --namespace=kustomize-lab
  statusCheckDeadlineSeconds: 600
