apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: letsencrypt-stage
spec:
  secretName: letsencrypt-stage
  dnsNames:
  - hello-world.aws.iteamdev.se
  acme:
    config:
    - dns01:
        ingressClass: traefik
        provider: route53
      domains:
      - hello-world.aws.iteamdev.se
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: register@iteam.se
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
      - name: route53
        route53:
          region: eu-north-1 # Also change to your needs
          accessKeyID: <VALID ACCESS KEY ID HERE> # I couldn't find a way to reference this directly from the secret
          secretAccessKeySecretRef:
            name: amazon-web-service-credentials
            key: AWS_SECRET_ACCESS_KEY