# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - api.yaml

# namespace to deploy all Resources to
namespace: kustomize-lab-dev

configMapGenerator:
  - name: api-properties
    env: api.properties # Note: which version of kustomize you use (standalone or included in skaffold can have issues)
  - name: common-properties
    env: common.properties
