apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: iteamse
  name: iteamse
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: iteamse
    spec:
      containers:
      - image: iteam1337/iteamse
        name: iteamse
        ports:
        - containerPort: 3000
        env:
         - name: PORT
           value: '3000'
         - name: RAZZLE_CMS_NODE_URL
           value: 'http://iteamse-cms:3000'
         - name: RAZZLE_HOST
           value: 'http://iteamse.kube.iteam:3000'
        resources: {}
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iteamse
spec:
  rules:
  - host: iteamse.kube.iteam
    http:
      paths:
      - backend:
          serviceName: iteamse
          servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: iteamse
  labels:
    io.kompose.service: iteamse
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: iteamse
status:
  loadBalancer: {}