apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: iteamse-cms
  name: iteamse-cms
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: iteamse-cms
    spec:
      containers:
      - image: iteam1337/iteamse-cms
        name: iteamse-cms
        ports:
        - containerPort: 3000
        env:
          - name: CONTENTFUL__SPACE
            valueFrom:
              secretKeyRef:
                key: space
                name: contentful-auth
          - name: CONTENTFUL__TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: contentful-auth
          - name: PORT
            value: '3000'
        resources: {}
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iteamse-cms
spec:
  rules:
  - host: iteamse-cms.kube.iteam
    http:
      paths:
      - backend:
          serviceName: iteamse-cms
          servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: iteamse-cms
  labels:
    io.kompose.service: iteamse-cms
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: iteamse-cms
status:
  loadBalancer: {}