---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: iteam1337/kustomize-lab-api
          ports:
            - containerPort: 4000
          env:
            - name: SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_URL
              value: db://best-database:5012
            - name: ENABLE_LOGGING
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: api
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: api
spec:
  tls:
    - hosts:
        - kustomize-lab-api.prod.iteamdev.io
      secretName: api-prod-tls
  rules:
    - host: kustomize-lab-api.prod.iteamdev.io
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 4000
