apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: api
spec:
  tls:
    - hosts:
        - kustomize-lab-api-prod.iteamdev.io
      secretName: api-tls
  rules:
    - host: kustomize-lab-api-prod.iteamdev.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
